---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: msa-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: msa-api
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: msa-api
  name: msa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: msa-api
    spec:
      containers:
      - image: shelleg/msa-api:config
        imagePullPolicy: Always
        name: msa-api
        ports:
        - containerPort: 8080
        resources: {}
status: {}
